### ISSUE TITLE
[suggestion] placeholderapi price type

### ISSUE THREAD

**Issue by austv** [magemonkeystudio/genesis#29]
Create a new PriceType to use a integer from a placeholder.
Example:

```
    RewardType: COMMAND
    Reward:
    - 'command'
    PriceType: PLACEHOLDER;playerdata_variable1
    Price: 5
```

You don't need to think how remove the price for this placeholder because we can just add a command for it, example:

```
    RewardType: COMMAND
    Reward:
    - 'give %player% diamond 1'
    - 'playerdata %player% remove variable1 5' #command from the plugin to remove the price from the variable
    PriceType: PLACEHOLDER;playerdata_variable1
    Price: 5
```

This way is much better than creating conditions to check if the player have the amount necessary and also you may in the future remove the amount from the integer, like DeluxeMenus.
