### ISSUE TITLE
Custom Heads still not fixed

### ISSUE THREAD

**Issue by LordRazen** [magemonkeystudio/genesis#51]
I checked the closed tasks yesterday and saw a few bugs with this message if you call a panel with custom heads: 

```
[09:38:56 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
```

It was told it was fixed with the latest version, so I downloaded bossshoppro-2.1.0-R0.6-20240222.041931-1.jar and run it with paper-1.20.4-408.jar - still the same issue. 

This here is one of the heads in that shop: 
```
  adminshop_hilfe:
    InventoryLocation: 28
    MenuItem: 
    - type:PLAYER_HEAD
    - customskull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmFkYzA0OGE3Y2U3OGY3ZGFkNzJhMDdkYTI3ZDg1YzA5MTY4ODFlNTUyMmVlZWQxZTNkYWYyMTdhMzhjMWEifX19
    - 'name:&a*Serverhilfe*'
    - 'lore:&7Hier kannst du zu den wichtigsten Bereichen des Servers Hilfe finden.#&c/help'
    RewardType: shop
    Reward: help
```
    
Maybe it helps finding the bug ;-)

Let me know if you need any further input.

**Comment by MaksyKun** [comment]
Could you please test it again with a newer Version of BossShopPro? Im using a similar setup but dont get the messages since the breaking change of 1.20.1 anymore:
```
farmwelt:
    RewardType: playercommand
    Reward: warp farmwelt
    MenuItem:
      - 'type:player_head'
      - 'customskull: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjIwZWU3NzQxZmYxYjk1OGRiYjlmYTdjZGRhZDljM2NjZTkzMzczZjQ3MGY5YjgzNGRhMDJkYTY3YzgyMDJhNCJ9fX0='
      - 'name:&9Farmwelt'
      - "lore:&bIn dieser Welt kannst du dir Resourcen"
      - "lore:&baneignen, um dich in den anderen Welten auszutoben."
      - "lore:&f"
      - "lore:&7Tätigkeiten:"
      - "lore:&7● &aItems farmen"
      - "lore:&7● &aGeld erarbeiten (Jobs)"
      - "lore:&7● &aErkunden & Looten"
      - "lore:&7● &aHaustiere suchen"
      - "lore:&7● &au.v.m."
    Message: ''
    InventoryLocation: 13
```
